a = int(input())
b = int(input())
print(f'{a} + {b} = {a+b}')
print(f'{a} - {b} = {a-b}')
print(f'{a} * {b} = {a*b}')
print(f'{a} // {b} = {a//b}')
print(f'{a}^{b} = {a**b}')
print(f'{a} % {b} = {a%b}')
print((a>b and "a > b") or "a < b")
print(a and b)
print(a or b)
print(not (a == b))
print(a >> 5)
print(b << 6)
print(f'hệ số 2 của {a} đảo ngược:',bin(a)[2:][::-1])
